Repository semjz/pyvengers-project, pull requests merged in 2023-11, with the labels that each got.

#23 Modify/postgres container and env
  .env-example
  config/settings.py
  docker-compose.yml
  requirements.txt
Labels: enhancement

#43 Setup redis
  config/settings.py
  requirements.txt
Labels: enhancement

#40 User model, manager and authentication
  authentication/__init__.py
  authentication/admin.py
  authentication/apps.py
  authentication/managers.py
  authentication/migrations/0001_initial.py
  authentication/migrations/0002_alter_user_user_id.py
  authentication/migrations/0003_alter_user_birth_date.py
  authentication/migrations/0004_rename_gender_user_gender_user_role.py
  authentication/migrations/0005_alter_user_managers_remove_user_user_id_and_more.py
  authentication/migrations/0006_alter_user_username.py
  authentication/migrations/0007_remove_user_username_user_user_id.py
  authentication/migrations/0008_rename_user_id_user_username.py
  authentication/migrations/0009_rename_username_user_user_id_alter_user_role.py
  authentication/migrations/0010_alter_user_email_alter_user_first_name_and_more.py
  authentication/migrations/0011_alter_user_national_code_alter_user_phone_number.py
  authentication/migrations/0012_alter_user_role.py
  authentication/migrations/__init__.py
  authentication/models.py
  authentication/serializers.py
  authentication/tests.py
  authentication/urls.py
  authentication/views.py
  config/settings.py
  config/urls.py
  requirements.txt
  university/urls.py
Labels: enhancement

#47 Course and termic course models
  university/models.py
Labels: enhancement

#75 Install apps again
  config/settings.py
  requirements.txt
  university/models.py
Labels: Fix bug

#77 Erfan model
  docs/ProjectERD-last version.jpg
  university/models.py
Labels: enhancement

#78 Finalize university models
  config/settings.py
  university/migrations/0001_initial.py
  university/models.py
Labels: enhancement

#48 Authentication register, login and logout tests
  authentication/tests.py
  authentication/views.py
Labels: enhancement

#80 Setup redis drf spectacular implement student creation
  authentication/choices.py
  authentication/managers.py
  authentication/migrations/0013_alter_user_role.py
  authentication/migrations/0014_alter_user_user_id.py
  authentication/models.py
  authentication/serializers.py
  authentication/urls.py
  authentication/views.py
  config/settings.py
  config/urls.py
  requirements.txt
  university/choices.py
  university/migrations/0002_alter_addandremove_status_alter_deleteterm_result_and_more.py
  university/migrations/0003_alter_course_type_and_more.py
  university/models.py
  university/permissions.py
  university/serializers.py
  university/urls.py
  university/views.py
Labels: enhancement

#82 Implement and use django role permissions
  authentication/choices.py
  authentication/managers.py
  authentication/migrations/0001_initial.py
  authentication/migrations/0002_alter_user_user_id.py
  authentication/migrations/0003_alter_user_birth_date.py
  authentication/migrations/0004_rename_gender_user_gender_user_role.py
  authentication/migrations/0005_alter_user_managers_remove_user_user_id_and_more.py
  authentication/migrations/0006_alter_user_username.py
  authentication/migrations/0007_remove_user_username_user_user_id.py
  authentication/migrations/0008_rename_user_id_user_username.py
  authentication/migrations/0009_rename_username_user_user_id_alter_user_role.py
  authentication/migrations/0010_alter_user_email_alter_user_first_name_and_more.py
  authentication/migrations/0011_alter_user_national_code_alter_user_phone_number.py
  authentication/migrations/0012_alter_user_role.py
  authentication/migrations/0013_alter_user_role.py
  authentication/migrations/0014_alter_user_user_id.py
  authentication/models.py
  authentication/roles.py
  authentication/serializers.py
  authentication/views.py
  config/settings.py
  requirements.txt
  university/migrations/0001_initial.py
  university/migrations/0002_alter_addandremove_status_alter_deleteterm_result_and_more.py
  university/migrations/0003_alter_course_type_and_more.py
  university/permissions.py
  university/serializers.py
Labels: enhancement

#87 Use viewset for IT manager student endpoints
  authentication/choices.py
  authentication/factories.py
  authentication/managers.py
  authentication/models.py
  authentication/serializers.py
  authentication/tests.py
  config/settings.py
  erd.pdf
  erd.png
  requirements.txt
  university/factories.py
  university/filtersets.py
  university/models.py
  university/serializers.py
  university/tests.py
  university/tests/__init__.py
  university/tests/admin_endpoint.py
  university/urls.py
  university/views.py
Labels: enhancement

#93 [MODIFY] TermCourse viewset added, admin professor and admin term added
  academic/models/course.py
  academic/permissions.py
  academic/serializers/course.py
  academic/urls.py
  academic/views.py
  config/settings.py
  management/filtersets/Professor.py
  management/models/members.py
  management/models/term.py
  management/serializers/professor.py
  management/serializers/term.py
  management/urls.py
  management/views.py
  utils/choices.py
Labels: enhancement

#101 Student receivable courses endpoints
  academic/factories.py
  academic/models/course.py
  academic/permissions.py
  academic/serializers/__init__.py
  academic/serializers/course.py
  academic/serializers/enrollment.py
  academic/serializers/student.py
  academic/tests/students.py
  academic/tests/subjects.py
  academic/urls.py
  academic/views/__init__.py
  academic/views/student_views.py
  management/factories.py
  management/models/members.py
  management/models/term.py
  management/serializers/__init__.py
  management/serializers/course.py
  management/views.py
  requirements.txt
  unitselection/models.py
  utils/choices.py
Labels: enhancement

#102 Implement sending email for password reset
  authentication/serializers/auth.py
  authentication/urls.py
  authentication/views.py
  config/settings.py
Labels: enhancement

#108 Add coverage package in requirements
  requirements.txt
Labels: documentation
